// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvg67NB-EKyMRAFJQo_d1EI_UuoOEcSFs',
    appId: '1:750217717728:web:3b96341bfea4acc2d5ed85',
    messagingSenderId: '750217717728',
    projectId: 'todoapp-23d4e',
    authDomain: 'todoapp-23d4e.firebaseapp.com',
    storageBucket: 'todoapp-23d4e.firebasestorage.app',
    measurementId: 'G-7WM7SKVJXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa4pChXqNm_q-_fun35eAV6Tu13yQ4rek',
    appId: '1:750217717728:android:d5b55278c07f196dd5ed85',
    messagingSenderId: '750217717728',
    projectId: 'todoapp-23d4e',
    storageBucket: 'todoapp-23d4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoiGO2tQxz-HaxFSXkWvv37_xL5BA1gHM',
    appId: '1:750217717728:ios:ea481cf191a7d0edd5ed85',
    messagingSenderId: '750217717728',
    projectId: 'todoapp-23d4e',
    storageBucket: 'todoapp-23d4e.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoiGO2tQxz-HaxFSXkWvv37_xL5BA1gHM',
    appId: '1:750217717728:ios:ea481cf191a7d0edd5ed85',
    messagingSenderId: '750217717728',
    projectId: 'todoapp-23d4e',
    storageBucket: 'todoapp-23d4e.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvg67NB-EKyMRAFJQo_d1EI_UuoOEcSFs',
    appId: '1:750217717728:web:e5f951c529081fafd5ed85',
    messagingSenderId: '750217717728',
    projectId: 'todoapp-23d4e',
    authDomain: 'todoapp-23d4e.firebaseapp.com',
    storageBucket: 'todoapp-23d4e.firebasestorage.app',
    measurementId: 'G-HQHL879DNX',
  );
}
